
/*	UNIVERSIDAD DE LAS FUERZAS ARMADAS ESPE
	DEPARTAMENTO DE CIENCIAS DE LA COMPUTACION
    INGENIERA DE SOFTWARE
                
	AUTORES:     ALEXANDER MAILA 
				JIMMY SIMBAÑA - jasimbana14@espe.edu.ec
	
	ENUNCIADO: REALIZAR UN PROGRAMA EN CLASES 			
				
	FECHA DE CREACION:        16-05-2022	
	FECHA DE MODIFICACION:    16-05-2022*/
#include<iostream>

class Suma {
	public:
		int suma(int);
};
